linx_api:
  base_url: "https://prataearte.layer.core.dcg.com.br"
  username: "rafael.betminds"
  password: "wyjbaf-3nufvI-rezryt"

bigquery:
  project_id: "datalake-betminds"
  dataset_id: "prataearte"
  table_id: "pedidos"  # Será criada automaticamente

# Configurações da tabela
table_schema:
  # Informações Básicas do Pedido
  - name: "order_id"
    type: "STRING"
    mode: "REQUIRED"
    description: "ID único do pedido"
  - name: "order_number"
    type: "STRING"
    mode: "REQUIRED"
    description: "Número do pedido"
  - name: "created_date"
    type: "TIMESTAMP"
    mode: "REQUIRED"
    description: "Data de criação do pedido"
  - name: "acquired_date"
    type: "TIMESTAMP"
    mode: "NULLABLE"
    description: "Data de aquisição do pedido"
  - name: "cancelled_date"
    type: "TIMESTAMP"
    mode: "NULLABLE"
    description: "Data de cancelamento do pedido"
  - name: "global_status"
    type: "INTEGER"
    mode: "REQUIRED"
    description: "Status global do pedido"
  - name: "order_status_id"
    type: "INTEGER"
    mode: "REQUIRED"
    description: "ID do status do pedido"
  - name: "total"
    type: "FLOAT"
    mode: "REQUIRED"
    description: "Valor total do pedido"
  - name: "subtotal"
    type: "FLOAT"
    mode: "REQUIRED"
    description: "Subtotal do pedido"
  - name: "delivery_amount"
    type: "FLOAT"
    mode: "REQUIRED"
    description: "Valor do frete"
  - name: "discount_amount"
    type: "FLOAT"
    mode: "REQUIRED"
    description: "Valor do desconto"
  - name: "tax_amount"
    type: "FLOAT"
    mode: "REQUIRED"
    description: "Valor dos impostos"

  # Informações do Cliente
  - name: "customer_id"
    type: "INTEGER"
    mode: "REQUIRED"
    description: "ID do cliente"
  - name: "customer_name"
    type: "STRING"
    mode: "REQUIRED"
    description: "Nome do cliente"
  - name: "customer_email"
    type: "STRING"
    mode: "NULLABLE"
    description: "Email do cliente"
  - name: "customer_cpf"
    type: "STRING"
    mode: "NULLABLE"
    description: "CPF do cliente"
  - name: "customer_cnpj"
    type: "STRING"
    mode: "NULLABLE"
    description: "CNPJ do cliente"
  - name: "customer_type"
    type: "STRING"
    mode: "REQUIRED"
    description: "Tipo do cliente (P - Pessoa, C - Empresa, G - Convidado)"
  - name: "customer_cell_phone"
    type: "STRING"
    mode: "NULLABLE"
    description: "Celular do cliente"
  - name: "customer_phone"
    type: "STRING"
    mode: "NULLABLE"
    description: "Telefone do cliente"
  - name: "customer_gender"
    type: "STRING"
    mode: "NULLABLE"
    description: "Gênero do cliente"
  - name: "customer_birth_date"
    type: "TIMESTAMP"
    mode: "NULLABLE"
    description: "Data de nascimento do cliente"

  # Endereço de Entrega
  - name: "delivery_address_line"
    type: "STRING"
    mode: "NULLABLE"
    description: "Rua do endereço de entrega"
  - name: "delivery_address_number"
    type: "STRING"
    mode: "NULLABLE"
    description: "Número do endereço de entrega"
  - name: "delivery_neighbourhood"
    type: "STRING"
    mode: "NULLABLE"
    description: "Bairro do endereço de entrega"
  - name: "delivery_city"
    type: "STRING"
    mode: "NULLABLE"
    description: "Cidade do endereço de entrega"
  - name: "delivery_state"
    type: "STRING"
    mode: "NULLABLE"
    description: "Estado do endereço de entrega"
  - name: "delivery_postal_code"
    type: "STRING"
    mode: "NULLABLE"
    description: "CEP do endereço de entrega"
  - name: "delivery_contact_name"
    type: "STRING"
    mode: "NULLABLE"
    description: "Nome do contato para entrega"
  - name: "delivery_contact_phone"
    type: "STRING"
    mode: "NULLABLE"
    description: "Telefone do contato para entrega"

  # Itens do Pedido (como RECORD)
  - name: "items"
    type: "RECORD"
    mode: "REPEATED"
    description: "Lista de itens do pedido"
    fields:
      - name: "ProductID"
        type: "STRING"
        description: "ID do produto"
      - name: "ProductName"
        type: "STRING"
        description: "Nome do produto"
      - name: "SKU"
        type: "STRING"
        description: "Código do produto"
      - name: "Qty"
        type: "FLOAT"
        description: "Quantidade"
      - name: "Price"
        type: "FLOAT"
        description: "Preço unitário"
      - name: "Total"
        type: "FLOAT"
        description: "Total do item"
      - name: "Weight"
        type: "FLOAT"
        description: "Peso"
      - name: "Width"
        type: "FLOAT"
        description: "Largura"
      - name: "Height"
        type: "FLOAT"
        description: "Altura"
      - name: "Depth"
        type: "FLOAT"
        description: "Profundidade"

  # Pagamento (como RECORD)
  - name: "payment_methods"
    type: "RECORD"
    mode: "REPEATED"
    description: "Lista de métodos de pagamento"
    fields:
      - name: "PaymentMethodID"
        type: "STRING"
        description: "ID do método de pagamento"
      - name: "Amount"
        type: "FLOAT"
        description: "Valor"
      - name: "Status"
        type: "STRING"
        description: "Status do pagamento"
      - name: "PaymentDate"
        type: "TIMESTAMP"
        description: "Data do pagamento"
      - name: "Installments"
        type: "INTEGER"
        description: "Número de parcelas"
      - name: "PaymentInfo"
        type: "STRING"
        description: "Informações detalhadas do pagamento"
      - name: "PaymentType"
        type: "STRING"
        description: "Tipo de pagamento"
      - name: "Provider"
        type: "STRING"
        description: "Provedor do pagamento"
      - name: "AuthorizationCode"
        type: "STRING"
        description: "Código de autorização"
      - name: "TransactionNumber"
        type: "STRING"
        description: "Número da transação"

  # Entrega (como RECORD)
  - name: "delivery_methods"
    type: "RECORD"
    mode: "REPEATED"
    description: "Lista de métodos de entrega"
    fields:
      - name: "CarrierName"
        type: "STRING"
        description: "Nome da transportadora"
      - name: "DeliveryMethodAlias"
        type: "STRING"
        description: "Alias do método"
      - name: "ETA"
        type: "STRING"
        description: "Tempo estimado de entrega"
      - name: "Amount"
        type: "FLOAT"
        description: "Valor do frete"

  - name: "shipment_status"
    type: "INTEGER"
    mode: "REQUIRED"
    description: "Status do envio"

  - name: "shipments"
    type: "RECORD"
    mode: "REPEATED"
    description: "Lista de envios"
    fields:
      - name: "ShipmentNumber"
        type: "STRING"
        description: "Número do envio"
      - name: "ShipmentStatus"
        type: "INTEGER"
        description: "Status do envio"

  # Informações do Vendedor
  - name: "seller_name"
    type: "STRING"
    mode: "NULLABLE"
    description: "Nome do vendedor"
  - name: "seller_email"
    type: "STRING"
    mode: "NULLABLE"
    description: "Email do vendedor"
  - name: "seller_phone"
    type: "STRING"
    mode: "NULLABLE"
    description: "Telefone do vendedor"
  - name: "seller_integration_id"
    type: "STRING"
    mode: "NULLABLE"
    description: "ID de integração do vendedor"

  # Metadados
  - name: "created_at"
    type: "TIMESTAMP"
    mode: "REQUIRED"
    description: "Data e hora de criação do registro" 